### ISSUE TITLE
《搭建证书透明度(certificate-transparency)日志服务之从入门到放弃 》这篇博客中的github链接没有了

### ISSUE THREAD

**Issue by YYRise** [razeencheng/razeencheng.github.io#1]
如题

**Comment by razeencheng** [comment]
Google已经不推荐用这个部署CT LOG Server了，项目的部署文档应该是被移除了。

这有一个过期说明。
https://github.com/google/certificate-transparency/blob/master/DEPRECATED.md


现在想搭建的话可以去看看Trillian项目，也是Google推荐的。

https://github.com/google/trillian
